#!/usr/bin/env python
"""
End-to-end pipeline: raw H5 → preprocessing → EM → validation → figures.

Processes raw BDSP PSG recordings (H5 format at 200Hz) through the full
HLG pipeline and cross-validates against pre-computed intermediate results.

Pipeline steps:
    1. Read raw H5 (signals + annotations at 200Hz)
    2. Resample to 10Hz, map stage/resp/arousal encodings
    3. Compute ventilation trace (Ventilation_ABD, d_i_ABD, arousal_locs)
    4. Segment into 8-min NREM/REM blocks
    5. Run Python EM algorithm on each segment
    6. Cross-validate against pre-computed reference CSVs
    7. Generate figures

Data layout:
    data/raw_h5/              Raw BDSP H5 recordings
    data/paper_examples/      Pre-computed reference CSVs (for validation)
    data/pipeline_output/     Pipeline output (generated by this script)

Usage:
    python -m scripts.run_end_to_end
    python -m scripts.run_end_to_end --study 7       # Single study
    python -m scripts.run_end_to_end --skip-em        # Only preprocess
"""

import argparse
import os
import time

import h5py
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.signal import decimate

from hlg.core.ventilation import create_ventilation_trace
from hlg.em.em_algorithm import run_em_on_segment
from hlg.em.loop_gain_calc import compute_loop_gain
from hlg.ss.segmentation import segment_data_based_on_nrem, compute_SS_score_per_segement

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
RAW_DIR = os.path.join(DATA_DIR, "raw_h5")
REF_DIR = os.path.join(DATA_DIR, "paper_examples")
OUT_DIR = os.path.join(DATA_DIR, "pipeline_output")
FIG_DIR = os.path.join(os.path.dirname(__file__), "..", "figures", "pipeline")

STUDY_MAP = {
    5:  {"h5": "sub-S0001111922082_ses-1.h5", "ref_csv": "NREM_OSA_Study_5.csv",    "group": "NREM_OSA",  "bdsp": 111922082},
    7:  {"h5": "sub-S0001111985952_ses-1.h5", "ref_csv": "HLG_OSA_Study_7.csv",      "group": "HLG_OSA",   "bdsp": 111985952},
    97: {"h5": "sub-S0001114591660_ses-1.h5", "ref_csv": "HLG_OSA_Study_97.csv",     "group": "HLG_OSA",   "bdsp": 114591660},
    99: {"h5": "sub-S0001116587855_ses-1.h5", "ref_csv": "high_CAI_Study_99.csv",    "group": "high_CAI",  "bdsp": 116587855},
}


# ─────────────────────────────────────────────────────────────────────
# Step 1: Read raw H5 and resample
# ─────────────────────────────────────────────────────────────────────

def load_raw_h5(h5_path: str, target_fs: int = 10) -> tuple[pd.DataFrame, dict]:
    """Read a raw BDSP H5 recording and resample to target_fs.

    Raw H5 layout:
        signals/abd, signals/chest, signals/spo2, signals/ptaf, ...
        annotations/stage, annotations/resp, annotations/arousal

    Returns a DataFrame at target_fs with columns matching the HLG
    pipeline convention, plus a header dict.
    """
    original_fs = 200

    with h5py.File(h5_path, "r") as f:
        abd_raw = f["signals/abd"][:, 0].astype(np.float64)
        spo2_raw = f["signals/spo2"][:, 0].astype(np.float64)
        stage_raw = f["annotations/stage"][:, 0].astype(np.float64)
        resp_raw = f["annotations/resp"][:, 0].astype(np.float64)
        arousal_raw = f["annotations/arousal"][:, 0].astype(np.float64)

    n_raw = len(abd_raw)
    factor = original_fs // target_fs

    # Resample signals via decimation
    abd = decimate(abd_raw, factor, zero_phase=True)
    spo2_dec = decimate(spo2_raw, factor, zero_phase=True)

    # Resample annotations by taking every factor-th sample (nearest-neighbor)
    stage = stage_raw[::factor]
    resp = resp_raw[::factor]
    arousal = arousal_raw[::factor]

    n = min(len(abd), len(stage), len(resp), len(arousal), len(spo2_dec))
    abd = abd[:n]
    spo2_dec = spo2_dec[:n]
    stage = stage[:n]
    resp = resp[:n]
    arousal = arousal[:n]

    # Map stage encoding: raw {0=W?, 1=N1, 2=N2, 3=N3, 4=REM, 5=W, 9=unscored}
    # → CSV {1=N1, 2=N2, 3=N3, 4=REM, 5=W, NaN=unscored/lights-off}
    stage_mapped = stage.copy()
    stage_mapped[stage == 0] = np.nan
    stage_mapped[stage == 9] = np.nan

    # Map respiratory events: raw {0=none, 1=obstructive, 2=central, 3=mixed, 7=hypopnea, 9=RERA}
    # → CSV {0=none, 1=obstructive, 2=central, 3=mixed, 4=hypopnea, 5=RERA}
    resp_mapped = np.zeros_like(resp)
    resp_mapped[resp == 1] = 1  # obstructive
    resp_mapped[resp == 2] = 2  # central
    resp_mapped[resp == 3] = 3  # mixed
    resp_mapped[resp == 7] = 4  # hypopnea
    resp_mapped[resp == 9] = 5  # RERA

    # Trim to sleep period: first to last scored epoch
    scored = np.where(np.isfinite(stage_mapped) & (stage_mapped > 0))[0]
    if len(scored) == 0:
        raise ValueError(f"No valid sleep staging found in {h5_path}")
    start_idx = scored[0]
    end_idx = scored[-1] + 1

    data = pd.DataFrame({
        "ABD": abd[start_idx:end_idx],
        "SpO2": spo2_dec[start_idx:end_idx],
        "Stage": stage_mapped[start_idx:end_idx],
        "Apnea": resp_mapped[start_idx:end_idx],
        "arousal": arousal[start_idx:end_idx],
    })

    # ind0/ind1: index into original 200Hz recording
    data["ind0"] = (np.arange(len(data)) + start_idx) * factor
    data["ind1"] = data["ind0"] + factor

    # Patient tag from filename
    basename = os.path.basename(h5_path)
    patient_tag = basename.replace(".h5", "")

    hdr = {
        "patient_tag": patient_tag,
        "newFs": target_fs,
        "Fs": original_fs,
        "n_raw_samples": n_raw,
        "trim_start": start_idx,
        "trim_end": end_idx,
    }

    return data, hdr


# ─────────────────────────────────────────────────────────────────────
# Step 2: Preprocess → EM-ready CSV
# ─────────────────────────────────────────────────────────────────────

def preprocess_to_csv(data: pd.DataFrame, hdr: dict, out_csv: str) -> pd.DataFrame:
    """Compute ventilation, segment, and export EM-ready CSV."""
    Fs = hdr["newFs"]

    # Compute ventilation trace
    data = create_ventilation_trace(data, Fs, plot=False)

    # Segment into 8-min NREM/REM blocks
    seg_dic = segment_data_based_on_nrem(data, Fs)

    # Compute SS scores per segment (uses Apnea for NaN handling;
    # ss_conv_score not available from raw, so set to 1.0 everywhere)
    data["ss_conv_score"] = 1.0
    ss_scores = compute_SS_score_per_segement(data, seg_dic)

    # Build export DataFrame
    export_cols = [
        "ind0", "ind1", "ABD", "Ventilation_ABD", "Eupnea_ABD",
        "d_i_ABD", "d_i_ABD_smooth", "arousal_locs", "Apnea",
        "Stage", "SpO2",
    ]
    export = data[export_cols].copy()

    # Add segment boundaries
    for key in seg_dic:
        export[key] = np.nan
        vals = seg_dic[key]
        export.loc[export.index[:len(vals)], key] = vals

    # Add SS scores
    for key in ss_scores:
        col = f"{key}_SS_score"
        export[col] = np.nan
        vals = ss_scores[key]
        export.loc[export.index[:len(vals)], col] = vals

    export["patient_tag"] = hdr["patient_tag"]
    export["Fs"] = Fs
    export["original_Fs"] = hdr["Fs"]
    export["breath_tag"] = "ptaf"

    os.makedirs(os.path.dirname(out_csv), exist_ok=True)
    export.to_csv(out_csv, index=False)
    return export


# ─────────────────────────────────────────────────────────────────────
# Step 3: Run EM on all segments
# ─────────────────────────────────────────────────────────────────────

def run_em_on_all_segments(csv_path: str) -> pd.DataFrame:
    """Run the Python EM algorithm on all NREM segments in a CSV."""
    T = pd.read_csv(csv_path)
    Fs = int(T["Fs"].iloc[0])

    nrem_starts = T["nrem_starts"].dropna().values.astype(int)
    nrem_ends = T["nrem_ends"].dropna().values.astype(int)

    results = []
    for i in range(len(nrem_starts)):
        start = int(nrem_starts[i])
        end = int(nrem_ends[i]) - 1
        if start == 0:
            start = 1
            end += 1
        end = min(end, len(T) - 1)
        seg = T.iloc[start : end + 1].copy().reset_index(drop=True)

        if len(seg) < 100:
            continue

        t0 = time.time()
        try:
            upAlpha, upgamma, uptau, V_o_est, h, u_min = run_em_on_segment(
                seg, w=5 * Fs, L=0.05, gamma_init=0.5, tau_init=15 * Fs, version="non-smooth"
            )
        except Exception as e:
            print(f"    Seg {i + 1}: FAILED ({e})")
            continue
        elapsed = time.time() - t0

        gamma = float(upgamma[-1])
        tau_sec = float(uptau[-1]) / Fs
        alpha = float(upAlpha[-1])
        LG = compute_loop_gain(0.05, gamma, u_min)

        results.append({
            "segment": i + 1,
            "start": start,
            "end": end,
            "gamma": gamma,
            "tau_sec": tau_sec,
            "alpha": alpha,
            "LG": LG,
            "u_min": u_min,
            "n_arousals": len(h),
            "time_sec": elapsed,
        })
        print(f"    Seg {i + 1}/{len(nrem_starts)}: LG={LG:.2f}, γ={gamma:.2f}, τ={tau_sec:.0f}s ({elapsed:.1f}s)")

    return pd.DataFrame(results)


# ─────────────────────────────────────────────────────────────────────
# Step 4: Cross-validate against reference
# ─────────────────────────────────────────────────────────────────────

def cross_validate(em_results: pd.DataFrame, ref_csv_path: str, Fs: int = 10) -> None:
    """Compare EM results with pre-computed reference CSV."""
    ref = pd.read_csv(ref_csv_path)

    ref_nrem_starts = ref["nrem_starts"].dropna().values.astype(int)
    ref_lg = ref["LG_nrem"].dropna().values
    ref_g = ref["G_nrem"].dropna().values
    ref_d = ref["D_nrem"].dropna().values

    print(f"\n    {'Metric':<12s} {'Pipeline':>10s}  {'Reference':>10s}  {'Match':>8s}")
    print(f"    {'─' * 46}")
    print(f"    {'N segments':<12s} {len(em_results):>10d}  {len(ref_nrem_starts):>10d}  {'✓' if len(em_results) == len(ref_nrem_starts) else '✗':>8s}")

    if len(em_results) > 0 and len(ref_lg) > 0:
        n = min(len(em_results), len(ref_lg))
        pipe_lg = em_results["LG"].values[:n]
        pipe_g = em_results["gamma"].values[:n]
        pipe_d = em_results["tau_sec"].values[:n]

        lg_corr = np.corrcoef(pipe_lg, ref_lg[:n])[0, 1] if n > 1 else float("nan")
        g_corr = np.corrcoef(pipe_g, ref_g[:n])[0, 1] if n > 1 else float("nan")
        d_corr = np.corrcoef(pipe_d, ref_d[:n])[0, 1] if n > 1 else float("nan")

        lg_mae = np.mean(np.abs(pipe_lg - ref_lg[:n]))
        g_mae = np.mean(np.abs(pipe_g - ref_g[:n]))
        d_mae = np.mean(np.abs(pipe_d - ref_d[:n]))

        print(f"    {'LG corr':<12s} {lg_corr:>10.4f}")
        print(f"    {'LG MAE':<12s} {lg_mae:>10.4f}")
        print(f"    {'γ corr':<12s} {g_corr:>10.4f}")
        print(f"    {'γ MAE':<12s} {g_mae:>10.4f}")
        print(f"    {'τ corr':<12s} {d_corr:>10.4f}")
        print(f"    {'τ MAE':<12s} {d_mae:>10.4f}")

        # Per-segment comparison for first few
        print(f"\n    First {min(5, n)} segments side-by-side:")
        print(f"    {'Seg':>4s}  {'LG_pipe':>8s} {'LG_ref':>8s}  {'γ_pipe':>8s} {'γ_ref':>8s}  {'τ_pipe':>8s} {'τ_ref':>8s}")
        for j in range(min(5, n)):
            print(
                f"    {j + 1:>4d}  {pipe_lg[j]:>8.3f} {ref_lg[j]:>8.3f}  "
                f"{pipe_g[j]:>8.3f} {ref_g[j]:>8.3f}  "
                f"{pipe_d[j]:>8.1f} {ref_d[j]:>8.1f}"
            )


# ─────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────

def process_study(study_num: int, skip_em: bool = False) -> None:
    """Run the full pipeline for one study."""
    info = STUDY_MAP[study_num]
    h5_path = os.path.join(RAW_DIR, info["h5"])
    ref_csv = os.path.join(REF_DIR, info["ref_csv"])
    out_csv = os.path.join(OUT_DIR, f"Study_{study_num}_{info['group']}.csv")
    em_csv = os.path.join(OUT_DIR, f"Study_{study_num}_{info['group']}_em_results.csv")

    print(f"\n{'═' * 70}")
    print(f"  Study {study_num} — {info['group']} (BDSP {info['bdsp']})")
    print(f"{'═' * 70}")

    # Step 1: Load raw H5
    print(f"\n  [1] Loading raw H5: {info['h5']}")
    t0 = time.time()
    data, hdr = load_raw_h5(h5_path)
    print(f"      {len(data)} samples at {hdr['newFs']}Hz ({len(data) / hdr['newFs'] / 3600:.1f}h)")
    print(f"      Trimmed: [{hdr['trim_start']}:{hdr['trim_end']}] of {hdr['n_raw_samples']} raw samples")
    print(f"      Time: {time.time() - t0:.1f}s")

    # Compare dimensions with reference
    ref = pd.read_csv(ref_csv)
    print(f"      Reference CSV: {len(ref)} rows")
    print(f"      Delta: {len(data) - len(ref)} rows ({(len(data) - len(ref)) / hdr['newFs']:.1f}s)")

    # Step 2: Preprocess
    print(f"\n  [2] Preprocessing: ventilation + segmentation...")
    t0 = time.time()
    export = preprocess_to_csv(data, hdr, out_csv)
    nrem_starts = export["nrem_starts"].dropna()
    nrem_ends = export["nrem_ends"].dropna()
    ref_nrem = ref["nrem_starts"].dropna()
    print(f"      NREM segments: {len(nrem_starts)} (reference: {len(ref_nrem)})")
    print(f"      Saved: {os.path.basename(out_csv)}")
    print(f"      Time: {time.time() - t0:.1f}s")

    if skip_em:
        print("\n  [3-4] Skipping EM (--skip-em)")
        return

    # Step 3: Run EM
    print(f"\n  [3] Running EM algorithm on {len(nrem_starts)} NREM segments...")
    t0 = time.time()
    em_results = run_em_on_all_segments(out_csv)
    em_results.to_csv(em_csv, index=False)
    print(f"      Completed {len(em_results)} segments in {time.time() - t0:.1f}s")
    print(f"      Saved: {os.path.basename(em_csv)}")

    # Step 4: Cross-validate
    print(f"\n  [4] Cross-validating against reference...")
    cross_validate(em_results, ref_csv)


def main():
    parser = argparse.ArgumentParser(description="End-to-end pipeline: raw H5 → EM → validation")
    parser.add_argument("--study", type=int, nargs="*", help="Study number(s) to process (default: all)")
    parser.add_argument("--skip-em", action="store_true", help="Only preprocess, skip EM")
    args = parser.parse_args()

    studies = args.study if args.study else sorted(STUDY_MAP.keys())

    print("=" * 70)
    print("  HLG End-to-End Pipeline")
    print("=" * 70)
    print(f"  Studies: {studies}")
    print(f"  Raw H5: {RAW_DIR}")
    print(f"  Reference: {REF_DIR}")
    print(f"  Output: {OUT_DIR}")

    t_total = time.time()
    for study_num in studies:
        process_study(study_num, skip_em=args.skip_em)

    print(f"\n{'=' * 70}")
    print(f"  Pipeline complete! Total: {time.time() - t_total:.0f}s")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
